development:
    username: username 
    password: password
    url: data.beta.mssds.com
    authority: authority
    
test:
    username: username 
    password: password
    url: data.beta.mssds.com
    authority: authority
    
production:
    username: username 
    password: password
    url: data.beta.mssds.com
    authority: authority